version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - '*'
  - package-ecosystem: nuget
    directory: /plugin/Jellyfin.Plugin.AlphaJump
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: nuget
    directory: /plugin/Jellyfin.Plugin.AlphaJump.Tests
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
